web-ap:
  build: "./web-ap" 
  ports:
    - "8888:443"
  volumes:
    - "./web-ap/app:/var/www/html"
  container_name: "web-ap"
db:
  image: postgres:10.6
  ports:
    - "5432:5432"
  volumes:
    - "./db:/var/lib/pgsql/data"
  container_name: "db"

